export let objStudents = {
  Student: [
    {
      id: 1,
      name: "adel",
      Gender: "Male",
      Job: "PROG",
      Age: 29,
      Skills: "GoolKepar",
      Mobile: "011 235 35 323",
    },
    {
      id: 2,
      name: "Alaa",
      Gender: "Male",
      Job: "FullStack",
      Age: 29,
      Skills: "FootBall",
      Mobile: "012 943 23 134",
    },
    {
      id: 3,
      name: "May",
      Gender: "Female",
      Job: "Programmer",
      Age: 19,
      Skills: "Reading",
      Mobile: "015 812 43 934",
    },
    {
      id: 4,
      name: "Randa",
      Gender: "Female",
      Job: "Teacher",
      Age: 25,
      Skills: "Teach",
      Mobile: "017 379 72 123",
    },
    {
      id: 5,
      name: "Omar",
      Gender: "Male",
      Job: "Teacher",
      Age: 23,
      Skills: "Boxing",
      Mobile: "012 943 26 577",
    },
    {
      id: 6,
      name: "Yasser",
      Gender: "Male",
      Job: "Doctor",
      Age: 43,
      Skills: "Racing",
      Mobile: "011 431 46 525",
    },
    {
      id: 7,
      name: "Safaaa",
      Gender: "Female",
      Job: "Minister",
      Age: 33,
      Skills: "Caring",
      Mobile: "010 673 139 812",
    },
    {
      id: 8,
      name: "Kholoud",
      Gender: "Female",
      Job: "Lawer",
      Age: 55,
      Skills: "Chatingggg",
      Mobile: "011 410 25 121",
    },
    {
      id: 9,
      name: "AMGAED",
      Gender: "Male",
      Job: "Saver",
      Age: 43,
      Skills: "Kallping",
      Mobile: "015 753 55 102",
    },
    {
      id: 10,
      name: "Issraa",
      Gender: "Female",
      Job: "KHaaaaa",
      Age: 23,
      Skills: "Homming",
      Mobile: "010 851 10 345",
    },
  ],
};
